version: '3'
services:
  server:
    build: .
    ports:
      - '3000:3000'
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
    ports:
      - '5432:5432'
    volumes:
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/init.sql