version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes: 
      - /app/node_modules
      - .:/app
    environment:
      - External_Port=3000
      - PGDATABASE=docker
      - PGUSER=docker
      - PGPASSWORD=123456
      - PGHOST=postgres
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=docker
    ports: 
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:127.0.0.1"